### ISSUE TITLE
你好！请问有关于内存的操作部分的一些实际代码例子吗？

### ISSUE THREAD

**Issue by yuanAIhan** [Ascend/samples#2]
想知道一些实际的代码例子关于内存处理这一块的！谢谢你！

**Comment by ascendhuawei** [comment]
Hi, 
You can refer to  
https://github.com/Ascend/samples/tree/master/cplusplus/level1_single_api/1_acl/2_memory_management
This is the current memory management samples we currently have. Please see if this helps.

Best Regards

**Comment by yuanAIhan** [comment]
> Hi,
> You can refer to
> https://github.com/Ascend/samples/tree/master/cplusplus/level1_single_api/1_acl/2_memory_management
> This is the current memory management samples we currently have. Please see if this helps.
> 
> Best Regards

no any code！

**Comment by ascendhuawei** [comment]
sorry, the samples are still under development. You may find the official document useful https://support.huaweicloud.com/intl/en-us/devg-cpp-cann202infer/atlasdevelopment_01_0068.html
Could you specify about what kind of memory management you are looking for?
