### ISSUE TITLE
yolov3.caffemodel train code

### ISSUE THREAD

**Issue by youngallien** [Ascend/samples#6]
https://modelzoo-train-atc.obs.cn-north-4.myhuaweicloud.com/003_Atc_Models/AE/ATC%20Model/Yolov3/yolov3.caffemodel
https://modelzoo-train-atc.obs.cn-north-4.myhuaweicloud.com/003_Atc_Models/AE/ATC%20Model/Yolov3/yolov3.prototxt

下载了上面的模型， 想知道这个模型的训练代码在哪里？

或者，其他版本的(yolov5)的训练代码？

关键是想知道把模型后处理（nms之类）包含在模型里面的部分代码。（pytorch,yolov5的更好）

非常感谢！

**Comment by ascendhuawei** [comment]
Hi, you can find training code from Ascend ModelZoo.
https://gitee.com/ascend/modelzoo
https://www.hiascend.com/en/software/modelzoo
