### ISSUE TITLE
README: Tag v0.6.0 is missing

### ISSUE THREAD

**Issue by zouzias** [Ascend/samples#7]
Hi,

It seems that the README has several broken links to the repository tags. Could you please git push the missing tags? Tags exist on the gitee repository.

Example of missing tag: https://github.com/Ascend/samples/tree/v0.6.0/

Cheers,
Tassos

**Comment by ascendhuawei** [comment]
Hi, thanks for pointing this out. 
As the tags/releases are actually from gitee, as a temp workaround, we will change the links to the gitee links.
