### ISSUE TITLE
batch处理图像输出结果错误

### ISSUE THREAD

**Issue by RRRRRayyyyy** [Ascend/samples#8]
参考ascend\samples-master\python\level2_simple_inference\1_classification\googlenet_imagenet_dynamic_batch\src\classify.py 中batch处理方法
![image](https://user-images.githubusercontent.com/109121546/204471129-f244279a-96f5-4184-b7e4-f52d2e72ba96.png)

多图输入进行推理后得到的结果是重复的最后一张图的结果

**Comment by ascendhuawei** [comment]
Hi, following the readme steps, we can run this same code without problem.
Could you provide more details about your experiment?
